<body>

    <div class="corpo">
        <div class="row">
            <div class="col-md-2 " id="menu">
                <div class="container">
                    <div class="text-center">
                        <a href="/dashboard"><img src="/img/logo.png" class="img-fluid rounded" alt="logo.png" width="150"></a>
                    </div>

                    <div>
                        <ul class="list-group text-start">

                            <li class="list-group-item list-group-item-action"><i class="fa-solid fa-box"></i><a href="/dashboard">Produtos</a></li>
                            <li class="list-group-item list-group-item-action"> <i class="fa-solid fa-angles-down"></i><a href="#">Adicionar</a></li>
                            <li class="list-group-item list-group-item-action"><i class="fa-regular fa-comment"></i><a href="/feedback">FeedBack</a></li>
                            <li class="list-group-item list-group-item-action"><i class="fa-solid fa-right-from-bracket"></i><a href="/sair">Sair</a></li>
                        </ul>
                    </div>
                </div>


            </div>

            <div class="col-md-10" id="form-cad">
                <div class="container mt-5 pb-5 ">


                </div>
            </div>
        </div>
    </div>


</body>