<body>
    <div id="login">

        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="/autenticar" method="post">
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Email:</label><br>
                                <input type="text" name="email" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Senha:</label><br>
                                <input type="password" name="senha" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <a href="/inscreverse" class="btn btn-info btn">Inscrever-se</a>
                                <input type="submit" class="btn btn-info btn-md" value="Entrar">
                            </div>
                            <?php if ($this->view->login == 'erro') { ?>
                                <div class="col">
                                    <div class="row">
                                        <span class="text text-danger">*Email e ou senha inválido(s)</span>
                                    </div>
                                </div>
                            <?php } ?>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>